-- Create the projects table
create table projects (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  description text not null,
  tech_stack text[] not null,
  link text,
  github text
);

-- Insert some sample data
insert into projects (title, description, tech_stack, link, github)
values
  (
    'Finance Dashboard',
    'A comprehensive dashboard for tracking personal expenses and investments with real-time data visualization.',
    ARRAY['React', 'D3.js', 'Supabase'],
    'https://example.com',
    'https://github.com'
  ),
  (
    'E-commerce Platform',
    'Minimalist online store with seamless checkout experience and administrative control panel.',
    ARRAY['Next.js', 'Stripe', 'Tailwind'],
    'https://example.com',
    'https://github.com'
  ),
  (
    'AI Content Generator',
    'SaaS application leveraging LLMs to help creators generate blog posts and social media captions.',
    ARRAY['TypeScript', 'OpenAI', 'PostgreSQL'],
    'https://example.com',
    'https://github.com'
  );

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table projects enable row level security;

-- Create a policy that allows anyone to view projects (public access)
create policy "Public projects are viewable by everyone"
  on projects for select
  using ( true );
